apriori_average_rule_accuracy: 0.44206273776133465
author: Sagnik Patra
cnn_accuracy: 0.925000011920929
cnn_batch_size: 16
cnn_epochs: 30
dataset_used: Global_Pollution_Analysis.csv
minimum_confidence: 0.4
minimum_support: 0.05
project_title: Global Pollution Analysis and Energy Recovery using Apriori Algorithm
random_forest_accuracy: 1.0
raw_dataset_included: false
readme_included: false
zip_created: false
